# Telecom Customer Churn Case Study

You have been provided with a dataset related to telecom customer churn. Each row in the dataset represents a unique customer, and the columns contain various attributes and information about these customers.

The data set includes information about:
- Churn Column: Indicates customer churn within the last month.
- Services Info: Subscribed services like phone, internet, etc.
- Account Details: Tenure, contract, billing, charges.
- Demographics: Gender, age, and family status.

## Load the dataset in a dataframe

In [16]:
#import necessary libraries
import pandas as pd
import numpy as np

In [ ]:
#1. import the provided dataset to dataframe (telecom_customer_churn.csv)
#2. change the settings to display all the columns
#3. check the number of rows and columns
#4. check the top 5 rows
df=pd.read_csv("telecom_customer_churn.csv")

In [ ]:
df

In [5]:
df.shape

(7043, 21)

In [6]:
df.head(5)

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
#display all the column names
df.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='str')

In [8]:
# Check if the dataset contains nulls
df.isnull()

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
#check the datatype of all columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        7043 non-null   str
 1   gender             7043 non-null   str
 2   senior_citizen     7043 non-null   int64
 3   partner            7043 non-null   str
 4   dependents         7043 non-null   str
 5   tenure             7043 non-null   int64
 6   phone_service      7043 non-null   str
 7   multiple_lines     7043 non-null   str
 8   internet_service   7043 non-null   str
 9   online_security    7043 non-null   str
 10  online_backup      7043 non-null   str
 11  device_protection  7043 non-null   str
 12  tech_support       7043 non-null   str
 13  streaming_tv       7043 non-null   str
 14  streaming_movies   7043 non-null   str
 15  contract           7043 non-null   str
 16  paperless_billing  7043 non-null   str
 17  payment_method     7043 non-null   str
 18  monthly_charges    7043 non-null   float64
 19  total_charges      7043 non-null   str
 20  churn              7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [12]:
# Fix the datatype
#convert the datatype of 'monthly_charges', 'total_charges', 'tenure' to numeric datatype (pd.to_numeric)
cols=['monthly_charges', 'total_charges', 'tenure']

for col in cols:
    df[col]=pd.to_numeric(df[col],errors='coerce')

Q1 - Calculate the mean, median, and mode of the monthly_charges column

In [19]:
mean = df['monthly_charges'].mean()
mean

np.float64(64.76169246059918)

In [20]:
median = df['monthly_charges'].median()
median

np.float64(70.35)

In [22]:
mode = df['monthly_charges'].mode()
mode

0    20.05
Name: monthly_charges, dtype: float64

Q2 - Calculate the 25th, 50th, and 75th percentiles of the total_charges column

In [23]:
df['total_charges'].quantile([0.25,0.5,0.75])

0.25     401.4500
0.50    1397.4750
0.75    3794.7375
Name: total_charges, dtype: float64

Q3 - Calculate the range of monthly_charges column?

Hint - Range is the difference between max and min of monthly_charges.

In [29]:
monthly_charges_range = df['monthly_charges'].max()-df['monthly_charges'].min()
monthly_charges_range

np.float64(100.5)

Q4 - What is the first quartile of the monthly_charges column for customers who have not churned?

In [35]:
# Filter for non-churned customers and calculate the 25th percentile
first_quartile_monthly_charges = df.loc[df['churn'] == 'No', 'monthly_charges'].quantile(0.25)
first_quartile_monthly_charges

np.float64(25.1)

Q5 - What is the third quartile of the total_charges column for customers who have churned?

In [38]:
third_quartile_monthly_charges = df.loc[df['churn'] == 'Yes', 'monthly_charges'].quantile(0.75)
third_quartile_monthly_charges

np.float64(94.2)

Q6-  What is the mode of the payment method column for customers who have churned?

In [41]:
mode = third_quartile_monthly_charges = df.loc[df['churn'] == 'Yes', 'monthly_charges'].mode()
mode

0    74.4
Name: monthly_charges, dtype: float64

Q7 - What is the mean of the total charges column for customers who have churned and have a month-to-month contract?

In [46]:
# Filter the rows based on the churn status and contract type
filter = df.loc[(df['churn']=='Yes') & (df['contract']=='month-to-month')]
# Calculate the mean of the total charges column
mean = df['total_charges'].mean()
# Print the result
mean

np.float64(2283.3004408418656)

Q8 - What is the median of the tenure column for customers who have not churned and have a two-year contract?

In [47]:
# Filter the rows based on the churn status and contract type
filter2 = df.loc[(df['churn']=='No') & (df['contract']=='Two year')]

# Calculate the median of the tenure column
median = filter2['tenure'].median() 

# Print the result
median

np.float64(64.0)